version: '3.9'
services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: playkorte-postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: playkorte
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    container_name: playkorte-redis
    ports:
      - "6379:6379"
volumes:
  pgdata:
